CREATE DATABASE exam_s3;
USE exam_s3;

CREATE TABLE ville (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE categorie (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE besoin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idCategorie INT,
    idVille INT,
    nom VARCHAR(255) NOT NULL,
    quantinte DOUBLE NOT NULL
);

CREATE TABLE don (
    id INT PRIMARY KEY AUTO_INCREMENT,
    idBesoin INT,
    quantinte DOUBLE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);